"""添加用户角色和激活状态字段

Revision ID: 827605f1ad30
Revises: a103d1f8a504
Create Date: 2025-09-24 16:56:17.608901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827605f1ad30'
down_revision: Union[str, None] = 'a103d1f8a504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 不支持直接添加 NOT NULL 字段，需要分步处理

    # 1. 先添加可空字段
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True, comment='用户角色：guest/user/admin/super_admin'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True, comment='用户是否激活'))

    # 2. 更新所有现有用户的默认值
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE users SET role = 'guest', is_active = 1 WHERE role IS NULL")
    )

    # 3. 对于 SQLite，我们保持字段为可空，但在应用层确保总是有值
    # 注意：SQLite 不支持修改列约束，所以我们在 ORM 层面确保非空
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
